[program:pinesaas-backend]
directory=/home/administrator/projects/pinesaas-crm/backend
command=/usr/bin/npm run start:prod
user=administrator
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
environment=NODE_ENV="production",HOST="127.0.0.1",PORT="30001",FRONTEND_URL="https://itms.cloudafk.xyz"
stdout_logfile=/home/administrator/projects/pinesaas-crm/backend/logs/backend.log
stderr_logfile=/home/administrator/projects/pinesaas-crm/backend/logs/backend-error.log

[program:pinesaas-frontend]
directory=/home/administrator/projects/pinesaas-crm/pinesaas-blogs
command=/usr/bin/npm run preview -- --host 127.0.0.1 --port 5174
user=administrator
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
environment=NODE_ENV="production"
stdout_logfile=/home/administrator/projects/pinesaas-crm/pinesaas-blogs/logs/frontend.log
stderr_logfile=/home/administrator/projects/pinesaas-crm/pinesaas-blogs/logs/frontend-error.log