import { ArrowUpRight, LogIn, X } from 'lucide-react'
import { type SyntheticEvent, useEffect, useState } from 'react'
import { dateLabel, getJson, sendJson, SESSION_ID } from '../lib/api'
import type { Comment, Section, Story } from '../types'

type ReaderModalProps = { story: Story; section: Section; authToken: string; authName: string; onClose: () => void; onOpenAuth: () => void }

export function ReaderModal({ story, section, authToken, authName, onClose, onOpenAuth }: ReaderModalProps) {
  const [comments, setComments] = useState<Comment[]>([])
  const [commentText, setCommentText] = useState('')
  const [error, setError] = useState('')
  const [loading, setLoading] = useState(false)
  useEffect(() => { const endpoint = section === 'news' ? `/news/${story.id}/view` : `/blogs/${story.id}/view`; sendJson(endpoint, { method: 'POST', body: JSON.stringify({ sessionId: SESSION_ID, duration: 1, scrolled: false }) }).catch(() => undefined); if (section === 'blogs') getJson<Comment[]>(`/comments/blog/${story.id}`).then(setComments).catch(() => setError('Comments could not be loaded.')).finally(() => setLoading(false)) }, [section, story.id])
  const addComment = async (event: SyntheticEvent<HTMLFormElement>) => { event.preventDefault(); if (!commentText.trim() || !authToken) return; try { const created = await sendJson<Comment>('/comments', { method: 'POST', headers: { Authorization: `Bearer ${authToken}` }, body: JSON.stringify({ blogId: story.id, content: commentText.trim() }) }); setComments((items) => [created, ...items]); setCommentText('') } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Comment could not be added.') } }
  return <div className="reader-backdrop" onClick={onClose}><article className="reader" role="dialog" aria-modal="true" aria-label={story.title} onClick={(event) => event.stopPropagation()}><button className="close-reader" onClick={onClose} aria-label="Close story"><X size={20} /></button><div className="reader-kicker">{story.category?.name || 'PineSaaS journal'} / {dateLabel(story.createdAt)}</div><h2>{story.title}</h2><p className="reader-excerpt">{story.excerpt}</p><div className="reader-content">{story.content ? story.content.split(/\n+/).map((paragraph) => <p key={paragraph}>{paragraph}</p>) : <p>This story is ready to be connected to its full content from the publication API.</p>}</div>{section === 'blogs' && <section className="comments"><div className="comments-heading"><h3>Conversation</h3><span>{comments.length} comments</span></div>{loading ? <p className="comment-muted">Loading comments...</p> : comments.length === 0 ? <p className="comment-muted">Be the first to add a thoughtful note.</p> : comments.map((comment) => <div className="comment" key={comment.id}><strong>{comment.author?.name || 'Reader'}</strong><small>{dateLabel(comment.createdAt)}</small><p>{comment.content}</p></div>)}{authToken ? <form className="comment-form" onSubmit={addComment}><p className="signed-in">Signed in as {authName || 'reader'}</p><textarea value={commentText} onChange={(event) => setCommentText(event.target.value)} placeholder="Add to the conversation" rows={3} required /><button className="outline-button" type="submit">Post comment <ArrowUpRight size={15} /></button></form> : <div className="comment-login-prompt"><p className="comment-muted">Sign in to join the conversation.</p><button className="text-button" onClick={onOpenAuth}>Open account sign in <LogIn size={15} /></button></div>}{error && <p className="comment-error">{error}</p>}</section>}</article></div>
}
